### DISCUSSION TITLE
How does watchedNamespaces work?

### DISCUSSION THREAD

**Discussion by xolott** [fluent/fluentd#4189] [Q&A]
I'm using the fluent operator. My architecture is 

Fluent Bit -> FluentD -> Loki

I tested Fluent Bit with the stdout output and the loki output and everything worked as expected.

Then I added Fluentd to the mix only to forward my logs from fluent-bit to loki. This is my config for fluentd:

```yaml
    apiVersion: "fluentd.fluent.io/v1alpha1"
    kind: "ClusterFluentdConfig"
    metadata:
      name : "cluster-fluentd-config"
      labels:
        "app.kubernetes.io/name": "fluentd"
        "config.fluentd.fluent.io/enabled": "true"
    spec:
      watchedNamespaces:
        - logging
        - metrics
        - cert-manager
        - default
        - ingress-controller
        - kube-node-lease
        - kube-public
        - kube-system
        - linkerd
      
      clusterOutputSelector:
        matchLabels:
          "output.fluentd.fluent.io/enabled": "true"

      clusterFilterSelector:
        matchLabels:
          "filter.fluentd.fluent.io/enabled": "true"
```

And it doesn't work. But, if I remove the `watchedNamespaces` part, Loki gets the logs from fluentd. I want to be able to filter the namespaces that I want to ignore using fluentd.

How does the `watchedNamespaces` setting works? Even if I include all the namespaces in the list it doesn't work.
