### DISCUSSION TITLE
failed to write data into buffer by buffer overflow action=:throw_exception

### DISCUSSION THREAD

**Discussion by naveenrpp2017** [fluent/fluentd#4506] [Q&A]
### Describe the bug

- I have deployed fluentd as kubernetes pod to upload the kubernetes log to AWS OpenSearch.

- Initially for first few days it was working properly(sending log to AWS OpenSearch), after few days the latest kubernetes logs was not available in AWS OpenSearch.

- So when i checked the fluentd pod logs i was able to see the below error:
**failed to write data into buffer by buffer overflow action=:throw_exception**

### To Reproduce

create fluentd as a kubernetes pod and use the below fluentd.conf from configuration tab which will send logs to AWS OpenSearch

### Expected behavior

logs needs to be sent continuously to AWS OpenSearch without buffer related error

### Your Environment

```markdown
- Fluentd version:1.16.5
- Operating system: Amazon Linux 2
- Kernel version: 5.10.210-201.852.amzn2.x86_64
```

### Your Configuration

```apache
# Input plugin to tail container logs
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  tag kubernetes.*
  read_from_head true
  <parse>
    @type multi_format
    <pattern>
      format json
      time_key @timestamp
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </pattern>
    <pattern>
      format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
      time_format %Y-%m-%dT%H:%M:%S.%N%:z
    </pattern>
  </parse>
</source>

# Kubernetes metadata filter
<filter kubernetes.**>
  @type kubernetes_metadata
</filter>

# Output plugin to send logs to OpenSearch
<match kubernetes.**>
  @type opensearch
  include_tag_key true
  host "opensearch domain"
  port "443"
  scheme https
  ssl_verify true
  ssl_version TLSv1_2
  index_name services_log
  include_timestamp true
  tag_key @log_name
  time_key @timestamp
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  buffer_chunk_limit 2M
  buffer_queue_limit 32
  flush_interval 5s
  max_retry_wait 30
  disable_retry_limit
  num_threads 8
</match>
```

### Your Error Log

```shell
2024-05-24 04:41:09 +0000 [warn]: #0 failed to write data into buffer by buffer overflow action=:throw_exception
2024-05-24 04:41:09 +0000 [warn]: #0 emit transaction failed: error_class=Fluent::Plugin::Buffer::BufferOverflowError error="buffer space has too many data" location="/fluentd/vendor/bundle/ruby/3.2.0/gems/fluentd-1.16.5/lib/fluent/plugin/buffer.rb:330:in `write'" tag="kubernetes.var.log.containers.service.log"
```

**Comment by daipom** [comment]
`failed to write data into buffer by buffer overflow action=:throw_exception`

This is not a bug.
This warning occurs when the buffer becomes full.

The amount of logs and the transfer rate need to be adjusted.

Is it possible that the pace of transfer is not keeping up with the pace of log generation?

**Reply by daipom** [reply]
Hmm, this could be the same phenomenon as

* #2411

**Reply by daipom** [reply]
I'm wondering if there is something causing the data to accumulate in the buffer.

**Reply by iamMrGaurav** [reply]
Same here, I am also facing this. tried scaling, changing conf and all no improvement. @daipom

**Reply by iamMrGaurav** [reply]
@daipom let me know if you have resolved this issue in any way or mitigated to some extent. Much needed.

**Reply by daipom** [reply]
@iamMrGaurav Sure!
Could you please share the config?

**Reply by iamMrGaurav** [reply]
@daipom , 

```yml
 elasticsearch:
    host: "-----------------------"
    include_timestamp: true
    reconnect_on_error: true
    reload_on_failure: true
    reload_connections: true
    include_tag_key: true
    logstash_format: true
    logstash_prefix: fluentd
    index_name: fluentd
    logstash_dateformat:  '%Y.%m.%d'
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: "----"
          key: "-----"
    buffer:
      timekey_use_utc: true
      chunk_limit_size: 32MB
      total_limit_size: 12288MB
      type: file
      path: "/fluentd/log/elastic-buffer"
      flush_thread_count: 8
      flush_interval: "1s"
      queue_limit_length: 4
      flush_mode: interval
      retry_forever: true
```
