### DISCUSSION TITLE
[Q&A] log file with timestamp failed

### DISCUSSION THREAD

**Discussion by diloper** [fluent/fluentd#4573] [Q&A]
### What is a problem?

I want a log filename in YYYYMMDDHHMM format,
but only see  /var/log/%Y-%m-%d.%H%M.log/.

Thank for any suggestion.

I use k3s with the following YAML.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
    <source>
      @type tail
      tag audit
      path /var/log/audit.log
      pos_file /var/log/audit.log.pos
      format none
    </source>
    <system>
      log_level info
    </system>  
    <match **>
      @type file
      path /var/log/%Y-%m-%d.%H%M.log
      <buffer time>
        timekey 1m
      </buffer>
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: log-writer-and-fluentd
  name: log-writer-and-fluentd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: log-writer-and-fluentd
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: log-writer-and-fluentd
    spec:
      initContainers:
        - name: init-log-file
          image: busybox:1.31
          command: ["touch", "/var/log/audit.log"]
          volumeMounts:
            - name: logs
              mountPath: /var/log
      containers:
        - name: log-writer
          image: busybox:1.31
          command:
            [
              "sh",
              "-c",
              "while true; do echo $(date +'%Y-%m-%dT%H:%M:%S') >> /var/log/audit.log; sleep 60; done",
            ]
          volumeMounts:
            - name: logs
              mountPath: /var/log
        - name: fluentd
          image: fluent/fluentd:v1.16-1
          env:
            - name: FLUENTD_CONF
              value: "fluentd.conf"
          volumeMounts:
            - name: logs
              mountPath: /var/log
            - name: fluentd-config
              mountPath: /fluentd/etc/fluentd.conf
              subPath: fluentd.conf
          ports:
            - containerPort: 24224
      volumes:
        - name: logs
          emptyDir: {}
        - name: fluentd-config
          configMap:
            name: fluentd-config
```

### Describe the configuration of Fluentd

```yaml
    <source>
      @type tail
      tag audit
      path /var/log/audit.log
      pos_file /var/log/audit.log.pos
      format none
    </source>
    <system>
      log_level info
    </system>  
    <match **>
      @type file
      path /var/log/%Y-%m-%d.%H%M.log
      <buffer time>
        timekey 1m
      </buffer>
    </match>
```

### Describe the logs of Fluentd

```shell
ls /var/log/%Y-%m-%d.%H%M.log/
buffer.b61e86c16a1517bf3e02573198f3822bc.log       buffer.b61e86c4ee5c81249764ea22f5c7dc6b2.log
buffer.b61e86c16a1517bf3e02573198f3822bc.log.meta  buffer.b61e86c4ee5c81249764ea22f5c7dc6b2.log.meta
```

### Environment

```markdown
- Fluentd version: fluentd 1.16.3
- TD Agent version:
- Fluent Package version:
- Docker image (tag):
- Operating system:
- Kernel version: 
   NAME="Alpine Linux"
   ID=alpine
   VERSION_ID=3.17.5
   PRETTY_NAME="Alpine Linux v3.17"
```
