### ISSUE TITLE
fluentd as service in docker-compose

### ISSUE THREAD

**Issue by ykolomiets** [fluent/fluentd#2608]
I have this docker-compose.yml: 
```
version: '3.7'

services:
  fluentd:
    image: fluent/fluentd:edge
    networks:
      - global
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd:/fluentd

  db:
    image: mongo:3.4-xenial
    container_name: db
    networks:
      - global
    volumes:
      - db:/data/db
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        tag: db

  main:
    build: main
    container_name: main
    networks:
      - global
    depends_on:
      - fluentd
      - db
      - group-server
    restart: always
    logging:
      driver: "fluentd"
      options:
        tag: main

  group-server:
    build: group-fight-server
    container_name: group
    networks:
      - global
    volumes:
      - group-fight-logs:/home/server/logs
    restart: always
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        tag: group

networks:
  global:
``` 
and this fluentd.conf:

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<match main>
  @type copy
  <store>
    @type file
    path /fluentd/log/main.*.log
  </store>
  <store>
    @type stdout
  </store>
</match>
<match group>
  @type copy
  <store>
    @type file
    path /fluentd/log/group.*.log
  </store>
  <store>
    @type stdout
  </store>
</match>
```

Docker version 19.03.2, build 6a30dfc
docker-compose version 1.24.1, build 4667896b

All starts as expected without errors, but nothing appears in console or files.
But if I restart container with `docker stop main && docker start main` logs will appear.

Interesting that if remove fluentd service completely from docker-compose.yml I receive:
```
ERROR: for group  Cannot start service group-server: failed to initialize logging driver: dial tcp 127.0.0.1:24224: connect: connection refused
ERROR: for db  Cannot start service db: failed to initialize logging driver: dial tcp 127.0.0.1:24224: connect: connection refused
ERROR: for group-server  Cannot start service group-server: failed to initialize logging driver: dial tcp 127.0.0.1:24224: connect: connection refused
```
