### ISSUE TITLE
Fluent-bit unable to ship logs to fluentd in docker due to EADDRNOTAVAIL

### ISSUE THREAD

**Issue by megamind79** [fluent/fluentd#2687]
I'm trying to setup the EFK stack with fluent-bit on docker containers. While I could push the logs from fluent-bit to elasticsearch, when I tried to integrate fluentd, I'm facing issues with it. This's the exact error msg:

> unexpected error error_class=Errno::EADDRNOTAVAIL error="Address not available - bind(2) for \"fluent-bit\" port 24224"\

The services in my docker-compose file:
```
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - type: bind
        source: ./config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    networks:
      - efk_1
  fluentd:
    image: fluent/fluentd:${FLBV}
    ports:
      - '24224:24224'
    volumes:
      - type: bind
        source: ./config/fluent.conf
        target: /fluentd/etc/fluent.conf
        read_only: true
    networks:
      - efk_1
    depends_on:
      - elasticsearch
  fluent-bit:
    image: fluent/fluent-bit:${FBITV}
    ports:
      - '2020:2020'
    volumes:
      - type: bind
        source: ./config/fluent-bit.conf
        target: /fluent-bit/etc/fluent-bit.conf
        read_only: true
      - type: bind
        source: ./sample_logs
        target: /var/log
    networks:
      - efk_1
    depends_on:
      - fluentd
```
Previously I directly pushed the logs from fluent-bit to elasticsearch like this without fluentd config anywhere:

```
[SERVICE]
    Flush   2
    Log_Level   debug

[INPUT]
    Name    tail
    Path    /var/log/log.txt

[OUTPUT]
    Name    es
    Match   *
    Host    elasticsearch
    Port    9200
```

This pushed the logs to elasticsearch successfully, but now I added fluentd in between, so fluent-bit will send the logs to fluentd, which will then push to elasticsearch.

fluent-bit conf:

```
[SERVICE]
    Flush   2
    Log_Level   debug

[INPUT]
    Name    tail
    Path    /var/log/log.txt

[OUTPUT]
    Name    forward
    Match   *
    Host    fluentd
```

fluentd conf:

```
<source>
    @type forward
    bind fluent-bit
</source>

<match **>
    @type stdout
</match>
```

This's giving me errors as they're not able to detect the address even though they're part of the same docker network.

These're the errors I'm getting:

> fluent-bit_1 | [2019/11/06 10:31:02] [error] [io] TCP connection failed: fluentd:24224 (Connection refused)

and

> fluentd_1 | 2019-11-06 10:31:02 +0000 [error]: #0 unexpected error error_class=Errno::EADDRNOTAVAIL error="Address not available - bind(2) for \"fluent-bit\" port 24224"

Can someone please help me know where I'm making a mistake?

**Comment by repeatedly** [comment]
> bind fluent-bit

What does parameter mean?

**Comment by megamind79** [comment]
since both fluent-bit and fluentd services are mentioned in docker-compose file, I assumed that  docker would automatically configure these addresses with their ports when used by their names. I also checked with 0.0.0.0 host, which gave 
 

> [error] [io] TCP connection failed: 0.0.0.0:24224 (Connection refused)

**Comment by repeatedly** [comment]
How about `bind 0.0.0.0`?

**Comment by megamind79** [comment]
I did try that and I got an error, which I mentioned in my previous comment

**Comment by repeatedly** [comment]
No, I mean fluentd side, not fluent-bit side.

**Comment by megamind79** [comment]
I did try that in fluentd side in fluent.conf, changed bind to 0.0.0.0 and the output on fluent-bit conf to the same ip.

**Comment by megamind79** [comment]
the same naming convention worked for elasticsearch though from fluent-bit, as in i gave host as elasticsearch in fluent-bit config, and it successfully forwarded logs to elasticsearch

**Comment by repeatedly** [comment]
Hmm... I see. I'm not familiar with docker-compose, so need help from other users.
In addition, asking it on docker community is also good.
If our docker image has a problem, we should fix it.

**Comment by repeatedly** [comment]
>  i gave host as elasticsearch in fluent-bit config

Yes, fluent-bit side configuration seems ok but `bind fluent-bit` is wrong. Because `bind` can't use remote address. See ERRORS: http://man7.org/linux/man-pages/man2/bind.2.html

**Comment by ganmacs** [comment]
I confirmed it worked. your configuration seems to wrong.

> I did try that in fluentd side in fluent.conf, changed bind to 0.0.0.0 and the output on fluent-bit conf to the same ip.

fluentd-bit config does not need to be changed `bind 0.0.0.0`.

```
Removing ekf_fluent-bit_1 ... done
Removing ekf_fluentd_1    ... done
Removing network ekf_default
fluentd uses an image, skipping
fluent-bit uses an image, skipping
Creating network "ekf_default" with the default driver
Creating ekf_fluentd_1 ... done
Creating ekf_fluent-bit_1 ... done
Attaching to ekf_fluentd_1, ekf_fluent-bit_1
fluentd_1     | chown: /fluentd/etc/fluent.conf: Read-only file system
fluentd_1     | 2019-11-07 08:47:19 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
fluent-bit_1  | Fluent Bit v1.2.2
fluentd_1     | 2019-11-07 08:47:19 +0000 [info]: using configuration file: <ROOT>
fluentd_1     |   <source>
fluentd_1     |     @type forward
fluentd_1     |     bind "0.0.0.0"
fluentd_1     |   </source>
fluentd_1     |   <match **>
fluentd_1     |     @type stdout
fluentd_1     |   </match>
fluentd_1     | </ROOT>
fluentd_1     | 2019-11-07 08:47:19 +0000 [info]: starting fluentd-1.3.2 pid=7 ruby="2.5.2"
fluent-bit_1  | Copyright (C) Treasure Data
fluent-bit_1  |
fluentd_1     | 2019-11-07 08:47:19 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
fluent-bit_1  | [2019/11/07 08:47:19] [debug] [storage] [cio stream] new stream registered: tail.0
fluent-bit_1  | [2019/11/07 08:47:19] [ info] [storage] initializing...
fluent-bit_1  | [2019/11/07 08:47:19] [ info] [storage] in-memory
fluent-bit_1  | [2019/11/07 08:47:19] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
fluent-bit_1  | [2019/11/07 08:47:19] [ info] [engine] started (pid=1)
fluent-bit_1  | [2019/11/07 08:47:19] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
fluent-bit_1  | [2019/11/07 08:47:19] [debug] [in_tail] inotify watch fd=19
fluent-bit_1  | [2019/11/07 08:47:19] [debug] [in_tail] scanning path /var/log/log.txt
fluent-bit_1  | [2019/11/07 08:47:19] [debug] [in_tail] add to scan queue /var/log/log.txt, offset=0
fluent-bit_1  | [2019/11/07 08:47:19] [debug] [router] match rule tail.0:forward.0
fluent-bit_1  | [2019/11/07 08:47:19] [ info] [sp] stream processor started
fluent-bit_1  | [2019/11/07 08:47:19] [debug] [in_tail] file=/var/log/log.txt read=110 lines=22
fluent-bit_1  | [2019/11/07 08:47:19] [debug] [in_tail] file=/var/log/log.txt promote to TAIL_EVENT
fluentd_1     | 2019-11-07 08:47:19 +0000 [info]: gem 'fluentd' version '1.3.2'
fluentd_1     | 2019-11-07 08:47:19 +0000 [info]: adding match pattern="**" type="stdout"
fluentd_1     | 2019-11-07 08:47:19 +0000 [info]: adding source type="forward"
fluentd_1     | 2019-11-07 08:47:19 +0000 [info]: #0 starting fluentd worker pid=17 ppid=7 worker=0
fluentd_1     | 2019-11-07 08:47:19 +0000 [info]: #0 listening port port=24224 bind="0.0.0.0"
fluentd_1     | 2019-11-07 08:47:19 +0000 [info]: #0 fluentd worker is now running worker=0
fluentd_1     | 2019-11-07 08:47:19.635439300 +0000 fluent.info: {"worker":0,"message":"fluentd worker is now running worker=0"}
fluent-bit_1  | [2019/11/07 08:47:20] [debug] [task] created task=0x7f4b77e430c0 id=0 OK
fluent-bit_1  | [2019/11/07 08:47:20] [debug] [out_forward] request 462 bytes to flush
fluent-bit_1  | [2019/11/07 08:47:20] [debug] [out_fw] 22 entries tag='tail.0' tag_len=6
fluentd_1     | 2019-11-07 08:47:19.495476100 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495491500 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495497500 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495503400 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495509300 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495516000 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495521900 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495527900 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495533700 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495540400 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495546400 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495553500 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495559700 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495565500 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495571400 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495577200 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495583100 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495589000 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495594800 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495605400 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495611300 +0000 tail.0: {"log":"test"}
fluentd_1     | 2019-11-07 08:47:19.495617200 +0000 tail.0: {"log":"test"}
```

docker-compose.yml
```
version: '3.2'
services:
  fluentd:
    image: fluent/fluentd
    ports:
      - '24224:24224'
    volumes:
      - type: bind
        source: ./config/fluent.conf
        target: /fluentd/etc/fluent.conf
        read_only: true
  fluent-bit:
    image: fluent/fluent-bit
    ports:
      - '2020:2020'
    volumes:
      - type: bind
        source: ./config/fluent-bit.conf
        target: /fluent-bit/etc/fluent-bit.conf
        read_only: true
      - type: bind
        source: ./sample_logs
        target: /var/log
    depends_on:
      - fluentd
```


config/fluent.conf

```
<source>
  @type forward
  bind 0.0.0.0
</source>

<match **>
  @type stdout
</match>
```

conf/fluent.conf

```
[SERVICE]
    Flush   2
    Log_Level   debug

[INPUT]
    Name    tail
    Path    /var/log/log.txt

[OUTPUT]
    Name    forward
    Match   *
    Host    fluentd
```
