### ISSUE TITLE
Fluentd v1 doesn't output logs for some containers

### ISSUE THREAD

**Issue by moleksyuk** [fluent/fluentd#3251]
**Describe the bug**
Fluentd doesn't create output log file for some containers.

**To Reproduce**
1. Create `docker-compose.yaml`.
2. Create `fluent.conf`.
3. Run `docker-compose up`.

**Actual results:** only logs file for mysql5 & fluentd containers are created:
- mysql5.log
- fluentd.20210216.log

**Expected behavior**
- nats.log file has to be created.

**Your Environment**

- Fluentd or td-agent version: `fluentd:latest` docker image (16/02/2021)
- Operating system: `macOS Big Sur 11.2.1`
- Kernel version: `20.3.0`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

docker-compose.yaml  
```yaml
version: '2.1'

services:

  mysql5:
    image: mysql:5.6.37
    logging:
      driver: fluentd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql --user=root --password=password --execute "SHOW DATABASES;"
      interval: 3s
      timeout: 1s
      retries: 20
    depends_on:
      fluentd:
        condition: service_started
    stop_grace_period: 30s

  nats:
    image: nats:2.1.9
    logging:
      driver: fluentd
    command: ["-m", "8222", "-DV", "--auth", "l0cal_t0ken"]
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    depends_on:
      fluentd:
        condition: service_started

  fluentd:
    image: fluentd
    command: ["-v"]
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/logs
    ports:
      - "24224:24224"
```

fluent.conf  
```
<source>
    @type forward
    port 24224
    bind 0.0.0.0
</source>

<match fluent.*>
    @type copy
    <store>
        @type file
        path /fluentd/logs/fluentd
        append true
        <buffer>
            @type memory
            flush_mode immediate
        </buffer>
        <format>
            @type single_value
        </format>
    </store>
</match>

<match *>
    @type copy
    <store>
        @type file
        path /fluentd/logs/${container_name}
        append true
        <buffer container_name>
            @type memory
            flush_mode immediate
        </buffer>
        <format>
            @type single_value
            message_key log
        </format>
    </store>
</match>
```

**Additional context**
I see this issue not only with NATS docker image, but we have for example our own docker image based on ubuntu 16 that starts   script and produce some `echo` messages and log file is also missed for it as well.

I used before fluentd v0.12 with custom plugins and it worked fine for any containers.
Fluentd v0.12 setup that works with NATS and other containers without any problem:

```
FROM fluent/fluentd:v0.12.42

WORKDIR /home/fluent

ENV PATH /home/fluent/.gem/ruby/2.2.0/bin:$PATH
ENV GEM_PATH /home/fluent/.gem/ruby/2.2.0:$GEM_PATH

RUN apk add --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install fluent-plugin-record-reformer \
 && sudo gem install fluent-plugin-parser \
 && sudo gem install fluent-plugin-samefile \
 && sudo gem install fluent-plugin-forest \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem

ENV FLUENTD_OPT=""
ENV FLUENTD_CONF="fluent.conf"
COPY $FLUENTD_CONF /fluentd/etc/

EXPOSE 24284
CMD fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
```
fluent.conf (v0.12)
```
<source>
@type forward
port 24224
bind 0.0.0.0
</source>

<match *>
@type record_reformer
renew_record false
enable_ruby false

tag reformed.${record["container_name"]}
</match>

<match reformed./*>
  @type forest
  subtype samefile
  <template>
    format single_value
    add_newline true
    message_key log
    path /fluentd/logs${tag_parts[1]}.log
  </template>
</match>

<match fluent.info>
  @type forest
  subtype samefile
  <template>
    format single_value
    add_newline true
    message_key log
    path /fluentd/logs/${tag}.log
  </template>
</match>
```

**Comment by moleksyuk** [comment]
**Update:**
Seems like fluentd v0.12 was lightweight vs v1 and started first, that's why I didn't have issue with it.
If I start my setup in steps to reproduce like this:
1. `docker-compose up -d fluentd`
2. Wait ~5 sec
3. `docker-compose up -d` 
Then everything works fine.

So, to make sure that fluentd is started we need to improve its setup with healtcheck and replace dependent services from `service_started` to `service_healty`.
Fixed `docker-compose.yaml`:
```yaml
version: '2.1'

services:

  mysql5:
    image: mysql:5.6.37
    logging:
      driver: fluentd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql --user=root --password=my-secret-pw --execute "SHOW DATABASES;"
      interval: 3s
      timeout: 1s
      retries: 20
    depends_on:
      fluentd:
        condition: service_healthy
    stop_grace_period: 30s

  nats:
    image: nats:2.1.9
    logging:
      driver: fluentd
    command: ["-m", "8222", "-DV", "--auth", "l0cal_t0ken"]
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    depends_on:
      fluentd:
        condition: service_healthy

  fluentd:
    image: fluentd
    command: ["-v"]
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/logs
    ports:
      - "24224:24224"
    healthcheck:
      test: nc -vz localhost 24224
      interval: 1s
      timeout: 1s
      retries: 5
```
