### ISSUE TITLE
TOMCAT Container Logs not pushing to Splunk

### ISSUE THREAD

**Issue by jaypalpatil** [fluent/fluentd#3272]
**Describe the bug**
Tomcat Container logs are not pushing to splunk but other containers logs are pushing to splunk. Other container logs path is '/var/logs' and path for tomcat logs is '/usr/local/tomcat/logs/erefill_*.log'.

**To Reproduce**

**Expected behavior**
Able to push the logs from - /usr/local/tomcat/logs/erefill_*.log

**Your Environment**

- Fluentd or td-agent version: `fluentd --1.9.1`
- Operating system: `cat /etc/os-release` : Ubuntu - Debian- 18.04.3 LTS (Bionic Beaver) 
- Kernel version: `uname -r` : 4.15.0-1060-aws

**Your Configuration**
We have manually deployed the manifest file and not using the HELM option. 

**Tomcat Conf File:**
![image](https://user-images.githubusercontent.com/79451242/109625573-7df42e00-7b65-11eb-8661-717b860f3dc6.png)

**Filter Stanza from Output Conf File :**
![image](https://user-images.githubusercontent.com/79451242/109625943-ee02b400-7b65-11eb-81b9-c5d5da5fb07b.png)

**Filter for Tomcat Logs which is added in output.conf file :**
```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: splunk-kubernetes-logging
  namespace: fluentd-amax
  labels:
    app: splunk-kubernetes-logging
    engine: fluentd
    version: 1.4.6
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: splunk-kubernetes-logging
  template:
    metadata:
      labels:
        app: splunk-kubernetes-logging
        version: 1.4.6
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '24231'
    spec:
      serviceAccountName: splunk-kubernetes-logging
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: splunk-fluentd-k8s-logs
        image: docker.io/splunk/fluentd-hec:1.2.4
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          privileged: false
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPLUNK_HEC_TOKEN
          valueFrom:
            secretKeyRef:
              name: splunk-kubernetes-logging
              key: splunk_hec_token
        - name: SSL_CERT_FILE
          value: "/fluentd/etc/splunk/hec_ca_file"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: "/var/log"
        - name: varapp
          mountPath: "/usr/local/tomcat/logs"
        - name: varlogdest
          mountPath: "/var/vcap/store/docker/docker/containers"
          readOnly: true
        - name: journallogpath
          mountPath: "/run/log/journal"
          readOnly: true
        - name: conf-configmap
          mountPath: "/fluentd/etc"
        - name: secrets
          mountPath: "/fluentd/etc/splunk"
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: "/var/log"
      - name: varapp
        hostPath:
          path: "/usr/local/tomcat/logs"
      - name: varlogdest
        hostPath:
          path: "/var/vcap/store/docker/docker/containers"
      - name: journallogpath
        hostPath:
          path: "/run/log/journal"
      - name: conf-configmap
        configMap:
          name: splunk-kubernetes-logging
      - name: secrets
        secret:
          secretName: splunk-kubernetes-logging
```

**Additional context**
**Specifications of Tomcat Logs :**
- Logs Format - log4j
- Time Format - yyyy-MM-dd HH:mm:ss,SSS
- Regex - ^(\d{4}+-\d+-\d+ \d+:\d+:\d+,\d+)|([\d+])|(\S+:\d+)|-|(\S+)|

**Queries :**
- Which parsing plugin should be used for log4j logs format..? And How..?
- Are above stanza's are correct, can you pls verify once.
