### ISSUE TITLE
timezone issue when using docker to start fluentd v1.11 container

### ISSUE THREAD

**Issue by DamonWz** [fluent/fluentd#3493]
### Describe the bug

Hi!
I just change fluentd version from 1.3.0-1 to 1.11 for using the function regular expression in match label. But the time is 8 hours later than host linux. And it returns normal when version back to 1.3.0-1.
Here`s my docker-compose.yml:

```
version: '3.4'
services:
  fluentd:
    image: .../fluentd:v1.11
    container_name: fluentd
    restart: always
    network_mode: host
    environment:
      - FLUENTD_CONF=fluentd.conf
      - FLUENT_UID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/fluentd:/data/fluentd:rw
      - ./conf:/fluentd/etc:ro
```

### To Reproduce

..

### Expected behavior

..

### Your Environment

```markdown
- Fluentd version:1.11
- TD Agent version:
- Operating system:
- Kernel version:Linux 3.10.0-1160.2.2.el7.x86_64 x86_64
```

### Your Configuration

..

### Your Error Log

```shell
..
```
