### ISSUE TITLE
Fluentd file output incorrect timezone

### ISSUE THREAD

**Issue by neilkane** [fluent/fluentd#3519]
### Describe the bug

I'm trying out file output but my log file is giving me an incorrect timezone.

Basically I have a fluentd daemonset forwarding to a remote fluentd instance, which will then output to a file. I don't think the issue is with my fluentd daemonset, hence I'll focus on my remote fluentd instance.

I'm running the remote instance using docker-compose (config below) with image v1.14-debian-1.

I can see that the log in the created file. However, I think the timestamp is not correct. Here's an example log output:
`2021-09-28T08:08:24+08:00       app.**.log {some log in json}`

My local time is `2021-09-28T16:08:24+08:00`, and this is what I am expecting as the timestamp, not `2021-09-28T08:08:24+08:00`.

Please help me and correct me if I made a mistake in my config. Thank you.

### To Reproduce

1. Run `fluent/fluentd:v1.14-debian-1` using the docker-compose.yml and fluent.conf described in this issue. 
2. Send some data to the fluentd instance.

### Expected behavior

The log timestamp should be the same as the local time including the timezone (UTC+8).

Example:
local time: `2021-09-28T16:08:24+08:00`
expected timestamp: `2021-09-28T16:08:24+08:00`
actual timestamp: `2021-09-28T08:08:24+08:00`

### Your Environment

```markdown
- Fluentd version: `v1.14-debian-1`
- Operating system: `Ubuntu 18.04.5`
- Kernel version: `4.15.0-154-generic`
- docker version: `20.10.8`
```

### Your Configuration

docker-compose.yml
```
version: '3.0'

services:
  fluentd:
    image: fluent/fluentd:v1.14-debian-1
    user: root
    container_name: fluentd
    volumes:
      - ./logs:/var/log/fluentd/
      - ./config:/fluentd/etc/
    ports:
      - 24224:24224/tcp
      - 24224:24224/udp
    environment:
      - TZ=Asia/Singapore
```

fluentd.conf:
```
<match app.**>
    @type file
    path /var/log/fluentd/app/log
    append true
    <buffer>
        timekey 1d
        timekey_use_utc false
        timekey_wait 10m
    </buffer>
</match>
<source>
    @type forward
    port 24224
    bind 0.0.0.0
</source>
```

### Your Error Log

```shell
No error messages.
```
