### ISSUE TITLE
fluentd not creating index for kubernetes worker nodes

### ISSUE THREAD

**Issue by sathishc58** [fluent/fluentd#3664]
### Describe the bug

fluentd is unable to create index in elasticsearch for worker nodes

**Environment**  

```
OS  :  Ubuntu

Kubernetes Version:  v1.23.3
FluentD runs on :  20.04.4

OS  :   Windows 10
ElasticSearch & Kibana :  7.9
```

Kubernetes runs with 1 master and 1 worker node

**Output of Pods**

```
root@master:/var/log/containers# kubectl get pods -o wide

NAME                               READY   STATUS             RESTARTS         AGE     IP             NODE        NOMINATED NODE   READINESS GATES
fluentd-gqfww                      1/1     Running            0                3h53m   10.244.0.96    *****-mst   <none>           <none>
fluentd-k2xhq                      1/1     Running            0                3h53m   10.244.1.154   *****-wo    <none>           <none>
```

**Output of ElasticSearch**  **### (Index got created only for  master-pod and NOT for worker-pod)**

```
[2022-03-09T15:46:04,710][INFO ][o.e.c.m.MetadataCreateIndexService] [CHN-120] [kubernetes-fluentd-gqfww-2022.03.09] creating index, cause [auto(bulk api)], templates [], shards [1]/[1]
[2022-03-09T15:46:06,116][INFO ][o.e.c.m.MetadataMappingService] [CHN-120] [kubernetes-fluentd-gqfww-2022.03.09/LfCg59kLRp-CcR7gXQvE4w] create_mapping [_doc]
```

**K8S fluentd daemonset YAML file**

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: default
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.7.3-debian-elasticsearch7-1.0
        env:
        - name:  FLUENT_ELASTICSEARCH_HOST
          value: "192.168.11.218"  #"10.30.3.28"
        - name:  FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "http"
        - name: FLUENT_UID
          value: "0"
        # X-Pack Authentication
        # =====================
        - name: FLUENT_ELASTICSEARCH_USER
          value: none
        - name: FLUENT_ELASTICSEARCH_PASSWORD
          value: none #"n+0K_yW6H+dU-BqbFkJQ"
        - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
          value: "false"
        - name: FLUENTD_ARGS
          value: --no-supervisor -vv
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-conf
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

```

### To Reproduce

**Install the following on Ubuntu**

```
Kubernetes v1.23.3
FluentD
```

**Install the following on Windows 10**

```
ElasticSearch 7.9
Kibana 7.9
```

### Expected behavior

fluentd should be able to create index in elasticsearch for worker nodes

### Your Environment

```markdown
- Fluentd version:  v1.7.3-debian-elasticsearch7-1.0
- TD Agent version:  N/A
- Operating system:  Ubuntu 20.04 (Fluentd) & Windows 10 (ElasticSearch-Kibana)
- Kernel version:
```

### Your Configuration

```apache
Install the following on Ubuntu

Kubernetes v1.23.3
FluentD


Install the following on Windows 10

ElasticSearch 7.9
Kibana 7.9
```

### Your Error Log

```shell
No errors are there in logs
```
