### ISSUE TITLE
Environment variable FLUENT_OJ_OPTION_MAX_NESTING doesn't work

### ISSUE THREAD

**Issue by lozuwa** [fluent/fluentd#3888]
### Describe the bug

Setting the variable FLUENT_OJ_OPTION_MAX_NESTING doesn't limit the nesting option of json.

### To Reproduce

Follow these steps to reproduce:

1. Install fluentd using the helm chart kokuwa/fluentd-elasticsearch version 13.3.0

Command to install:
```bash
helm repo add kokuwa https://kokuwaio.github.io/helm-charts
helm install fluentd kokuwa/fluentd-elasticsearch --version=13.3.0 -f values.yaml
```

Values:
```yaml
elasticsearch:
  buffer:
    chunkLimitSize: "2M"
  hosts: ["elasticsearch-client:9200"]
  outputType: elasticsearch_dynamic
  suppressTypeName: true
  logstash:
    prefix: "logstash"
  scheme: "http"

env:
  FLUENT_OJ_OPTION_MAX_NESTING: 2
  
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi
```

Please note:
* Fluentd version installed with this chart version is `fluentd-1.14.4`
* FLUENT_OJ_OPTION_MAX_NESTING has been set to 2

2. Start sending logs from a pod with nested json objects

3. Check fluentd logs. FLUENT_OJ_OPTION_MAX_NESTING doesn't do anything

```bash
2022-09-07 19:16:44.313879242 +0000 fluent.error: {"message":"[elasticsearch] Could not push log to Elasticsearch:
...
 \"caused_by\"=>{\"type\"=>\"illegal_argument_exception\", \"reason\"=>\"Limit of total fields [1000] has been exceeded while adding new fields [1]\"}}}}]}"}
```

### Expected behavior

FLUENT_OJ_OPTION_MAX_NESTING should limit max nesting

### Your Environment

```markdown
- Fluentd version: fluentd-1.14.4
- TD Agent version: N/A
- Operating system: Provided by docker image quay.io/fluentd_elasticsearch/fluentd:v3.4.0
- Kernel version: Provided by docker image quay.io/fluentd_elasticsearch/fluentd:v3.4.0
```

### Your Configuration

```apache
Helm chart with values


elasticsearch:
  buffer:
    chunkLimitSize: "2M"
  hosts: ["elasticsearch-client:9200"]
  outputType: elasticsearch_dynamic
  suppressTypeName: true
  logstash:
    prefix: "logstash"
  scheme: "http"

env:
  FLUENT_OJ_OPTION_MAX_NESTING: 2
  
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi
```
```


### Your Error Log

```shell
Here are the fluentd logs. FLUENT_OJ_OPTION_MAX_NESTING doesn't do anything


2022-09-07 19:16:44.313879242 +0000 fluent.error: {"message":"[elasticsearch] Could not push log to Elasticsearch:
...
 \"caused_by\"=>{\"type\"=>\"illegal_argument_exception\", \"reason\"=>\"Limit of total fields [1000] has been exceeded while adding new fields [1]\"}}}}]}"}
```
