### ISSUE TITLE
path placeholders in @type file are not resolved

### ISSUE THREAD

**Issue by Dennis14e** [fluent/fluentd#4341]
### Describe the bug

Placeholders in path of type file are not resolved.
I use the source type "forward", from which I get systemd logs from fluent-bit (OUTPUT.name "forward").
I match the tag debian.** and the data is routed correctly, but the paths are wrong (e.g. `${tag}` instead of `debian.host.systemd._SYSTEMD_UNIT` or `%Y%m%d` instead of `20231113`.

### To Reproduce

docker-compose.yml

```yaml
version: "3"
services:
  fluentd:
    image: fluent/fluentd:edge-debian
    restart: unless-stopped
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./data/conf:/fluentd/etc
      - ./data/tls:/fluentd/tls
      - ./data/logs:/fluentd/logs
    user: "0:0"
    environment:
      - FLUENT_UID=0
      - FLUENT_GID=0
```

fluent-bit.conf
```ini
[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  On
    http_listen  127.0.0.1
    http_port    2020
    health_check On
    storage.metrics on
    storage.path /var/log/flb-storage/
    storage.sync normal
    storage.checksum off
    storage.max_chunks_up 128
    storage.backlog.mem_limit 5M
    storage.delete_irrecoverable_chunks on

[INPUT]
    name systemd
    storage.type filesystem
    tag debian.host.systemd.*
    db /var/lib/fluent-bit/systemd.db

[OUTPUT]
    name          forward
    storage.total_limit_size 50M
    match         *
    host          fluentd-host.tld
    port          24224
    tls           on
    tls.verify    on
    self_hostname fluent-bit-host.tld
    shared_key    arndkey
    username      user
    password      pass
```

### Expected behavior

Current path (wrong):
`./logs/${tag}/file.%Y%m%d/`

Expected path:
`./logs/debian.host.systemd._SYSTEMD_UNIT/file.20231113/`

### Your Environment

```markdown
- Fluentd version: 1.16.2 (docker image fluent/fluentd:edge-debian)
- Operating system: Debian GNU/Linux 11 (bullseye) (docker host)
- Kernel version: 5.10.0-26-amd64 (docker host)
```

### Your Configuration

```apache
<source>
  @type forward
  port 24224
  bind 0.0.0.0

  <transport tls>
    cert_path /fluentd/tls/server.crt
    private_key_path /fluentd/tls/server.key
  </transport>

  <security>
    self_hostname fluentd-host.tld
    shared_key arndkey
    user_auth true

    <user>
      username user
      password pass
    </user>
  </security>
</source>

<match debian.**>
  @type file
  path /fluentd/logs/${tag}/file.%Y%m%d

  <buffer tag, time>
    timekey 1d
    timekey_use_utc true
    timekey_wait 10m
  </buffer>
</match>

<match **>
  @type stdout
</match>
```

### Your Error Log

```shell
no error log
```
