### ISSUE TITLE
[YAML] 'log_level' is deprecated parameter name. use '@log_level' instead // parameter '$log_level' is not used

### ISSUE THREAD

**Issue by ng-bsy** [fluent/fluentd#4463]
### Describe the bug

`log_level` on plugin scope can't be correctly defined in yaml config, without fluentd throwing a warning and/or the parameter not being recognized

### To Reproduce

```yaml
# Config 1
- match:
    $tag: '**'
    $type: stdout
    log_level: debug
```
results in:
```
[warn]: #0 'log_level' is deprecated parameter name. use '@log_level' instead.
```
since `@` is not supported in yaml and every other instance of it has been replaced by `$`, looking at the [fluentd documentation](https://docs.fluentd.org/configuration/config-file-yaml#special-yaml-elements), I've also tried:
```yaml
# Config 2
- match:
    $tag: '**'
    $type: stdout
    $log_level: debug
```
however this results in:
```
[warn]: parameter '$log_level' in <match **>
...
</match> is not used.
```

### Expected behavior

I expect Config 2 not to throw a warning message and instead set the log_level at plugin scope to the according value.

### Your Environment

```markdown
- Fluentd version: 1.16.2
- TD Agent version:
- Operating system: Ubuntu 22.04 LTS
- Kernel version: 5.15
```

### Your Configuration

```apache
see To Reproduce
```

### Your Error Log

```shell
see To Reproduce
```
