### ISSUE TITLE
Configuration as yaml/json

### ISSUE THREAD

**Issue by warmfusion** [fluent/fluentd#554]
I've been trying to setup a FluentD puppet module that is able to build configuration from resource calls, however, the configuration syntax makes this very difficult.

Is it possible to use yaml or json for the configuration of this application as I would like to be able to
- Define sub-elements using a hierarchy of hashes
- Avoid having to declare 'footer' elements ( eg `</match>` )
## Example Configuration

```
fluentd::match:
    pattern: 'nginx.*'
    priority: 10
    options:
      type: copy
      store:
       - type: 'file'
         path: '/var/log/fluent/myapp'
         time_slice_format: '%Y%m%d'
         time_slice_wait: '10m'
         time_format: '%Y%m%dT%H%M%S%z'
         compress: 'gzip'
       - type: 'mongo'
         host: 'fluentd'
         port: '27017'
         database: 'fluentd'
         collection: 'test'
```
